# Generated by Django 4.1 on 2022-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                editable=False,
                null=True,
                upload_to="cat_img",
            ),
        ),
    ]
