# Generated by Django 4.1 on 2022-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_icon_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="cat_img"
            ),
        ),
    ]
