# Generated by Django 4.1 on 2023-01-08 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 0, 14, 50, 486990)),
        ),
    ]
