# Generated by Django 4.1 on 2023-01-10 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 17, 22, 6, 638622)),
        ),
    ]
