# Generated by Django 4.1 on 2023-06-19 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 23, 9, 42, 836599)),
        ),
    ]
