# Generated by Django 4.1 on 2022-10-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="detailsproduct",
            options={"verbose_name": "detail", "verbose_name_plural": "details"},
        ),
    ]
