# Generated by Django 4.1 on 2022-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_colorproduct_alter_detailsproduct_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorproduct",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
