# Generated by Django 4.1 on 2022-10-05 23:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_colorproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorproduct",
            name="data",
            field=jsonfield.fields.JSONField(),
        ),
    ]
