# Generated by Django 4.1 on 2022-10-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_colorproduct_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorproduct",
            name="data",
            field=models.JSONField(),
        ),
    ]
